# swagger文档配置
knife4j:
  enable: false
  setting:
    language: zh_cn
springdoc:
  default-flat-param-object: true
  swagger-ui:
    # 是否开启swagger-ui，【生产环境】建议关闭
    enabled: false
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha·
  api-docs:
    # 是否开启api-docs，【生产环境】建议关闭
    enabled: false
    path: /v3/api-docs
  group-configs:
    - group: 'admin'
      paths-to-match: '/**'
      packages-to-scan: com.sz.admin
    - group: 'generator工具'
      paths-to-match: '/**'
      packages-to-scan: com.sz.generator
    - group: 'www网站'
      paths-to-match: '/**'
      packages-to-scan: com.sz.www
    - group: '微信小程序'
      paths-to-match: '/**'
      packages-to-scan: com.sz.applet
