oss:
  # 支持S3协议的厂商
  provider: MINIO
  endpoint: 192.168.56.101:9000
  accessKey: a4jtJvgEmk4ead5dzac6
  secretKey: UW6kxTGRetIAahV759rFkgoQ8ilXLRUMW0ULdIoo
  bucketName: test
  richtextBucketName: static
  domain: http://192.168.56.101:9000
  # 命名方式: UUID、ORIGINAL原文件名偏好，冲突会补充时间
  naming: original
  scheme: https
  allowedExts:
    # 图片
    - jpg
    - jpeg
    - png
    - gif
    - bmp
    - webp
    - svg
    - ico
    # 文档
    - pdf
    - doc
    - docx
    - xls
    - xlsx
    - ppt
    - pptx
    - rtf
    - txt
    - csv
    - odt
    - ods
    - odp
    - pages
    - numbers
    - keynote
    # 压缩包
    - zip
    - rar
    - 7z
    - tar
    - gz
    # 音频格式
    - mp3
    - wav
    - ogg
    # 视频格式
    - mp4
    - mov
    - avi
    - wmv
  allowedMimeTypes:
    # 图片
    - image/jpeg
    - image/pjpeg
    - image/png
    - image/gif
    - image/bmp
    - image/webp
    - image/svg+xml
    - image/vnd.microsoft.icon
    # 文档
    - application/pdf
    - application/msword
    - application/vnd.openxmlformats-officedocument.wordprocessingml.document
    - application/vnd.ms-excel
    - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
    - application/vnd.ms-powerpoint
    - application/vnd.openxmlformats-officedocument.presentationml.presentation
    - application/rtf
    - text/plain
    - text/csv
    - application/vnd.oasis.opendocument.text
    - application/vnd.oasis.opendocument.spreadsheet
    - application/vnd.oasis.opendocument.presentation
    - application/vnd.apple.pages
    - application/vnd.apple.numbers
    - application/vnd.apple.keynote
    # 压缩包
    - application/zip
    - application/x-zip-compressed
    - application/x-rar-compressed
    - application/x-7z-compressed
    - application/x-tar
    - application/gzip
    - application/x-gzip
    # 音频
    - audio/mpeg
    - audio/wav
    - audio/ogg
    # 视频
    - video/mp4
    - video/quicktime
    - video/x-msvideo
    - video/x-ms-wmv
    # 二进制
    - application/octet-stream